language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-19

env:
  global:
    secure: QpUtfmGzlk2j90qBzSFo35ALFwqjS4phh94JJonIb0KyF3JfpN5z8i915/M6mFhCIiVvCJR7zJYjS5C60OL0RL+HkLkXXZ2WP5VPB6wUzzvIVax5Q+7z+VvhDkPHQwpYG8KkXq6eHqgJGSD/R9cRbc/KhQEhrxxrqQD5fw/Gpkc=

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - ./gradlew connectedAndroidTest
  - android list target
  - ./gradlew test --stacktrace

  #- ./gradle
  #- ./gradlew clean assemble check generateReleaseJavadoc --info --stacktrace

  #- ./gradlew check -PdisablePreDex --continue --stacktrace
   # - android-wait-for-emulator
    #- adb devices
   # - adb shell input keyevent 82 &amp;
    #- ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

after_success:
  - .utility/publish-javadoc.sh
  - bash <(curl -s https://codecov.io/bash)

sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.10